### ISSUE TITLE
Update `hs-bindgen-traits` and `hs-bindgen-attribute` versions to 0.9

### ISSUE THREAD

**Issue by Eisverygoodletter** [yvan-sraka/hs-bindgen#9]
Currently `hs-bindgen` is on version `0.8` and uses version `0.8` of `hs-bindgen-traits` and `hs-bindgen-attribute` but `0.9` is the newest version for both.

There's a fix in `hs-bindgen-types` version `0.9` that [resolves a conflicting trait impl problem on windows](https://github.com/yvan-sraka/hs-bindgen-types/issues/2). Currently I'm using Windows and can't use the fix `hs-bindgen-types` version `0.9` because `hs-bindgen` uses `0.8` versions of the crates. This means the current version of `hs-bindgen` published to crates.io cannot be compiled on windows.

The solution would involve updating https://github.com/yvan-sraka/hs-bindgen/blob/755ff02560730ef2fbc58d9d72e1553d7dda1834/Cargo.toml#L16-L17
to
```toml
hs-bindgen-attribute = { version = "0.9", default-features = false } 
hs-bindgen-traits = { version = "0.9", default-features = false } 
```
and publishing a new version of `hs-bindgen`. 
Alternatively, if publishing a new version isn't possible, I could import `hs-bindgen-traits` and `hs-bindgen-attribute` separately (from what I understand, `hs-bindgen` is only used for grouping `hs-bindgen-traits` and `hs-bindgen-attribute` together)
